---
- name: Install build-essential
  apt: name="build-essential" state=present

- name: Install libsqlite3-dev
  apt: name="libsqlite3-dev" state=present

- name: Install ruby-dev
  apt: name="ruby-dev" state=present

- name: Install gem mime-types
  shell: gem install mime-types --version "< 3"

- name: Install mailcatcher
  shell: gem install --conservative mailcatcher

- name: Set up Mailcathcer as a daemon
  template: src=mailcatcher_service.j2 dest=/etc/init.d/mailcatcher mode=0755

- name: Set up Mailcathcer for start up when system boot
  shell: update-rc.d mailcatcher defaults
  when: mailcatcher_startup_on_boot == true

- name: Start Mailcathcer
  service: name=mailcatcher state=started

- name: Install Mailcathcer as php module
  template: src=mailcatcher_php.j2 dest="/etc/php/{{ mailcatcher_php_version }}/mods-available/mailcatcher.ini"

- name: Enable Mailcathcer php module
  shell: phpenmod -v {{ mailcatcher_php_version }} mailcatcher